import { type NextPage } from "next";
import Head from "next/head";
import { toast } from "react-hot-toast";
import { api } from "~/utils/api";
import { AiOutlineDelete } from 'react-icons/ai';

const Home: NextPage = () => {

  const { mutateAsync: createUser } = api.users.createUser.useMutation();
  const { data, refetch } = api.users.getUsers.useQuery();
  const { mutateAsync: deleteuser } = api.users.deleteUser.useMutation();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <form
          className="flex flex-col items-center justify-center py-2"
          onSubmit={(e) => {
            e.preventDefault()
            const formData = new FormData(e.target as HTMLFormElement)
            const name = formData.get('name') as string;
            createUser({ name: name }).then(() => {
              toast.success(`Created user ${name}`);
              refetch();
            })
          }}>
          <input
            type="text"
            name="name"
            placeholder="Name"
            className="p-4 mb-4 text-2xl border border-gray-300 rounded-md"
          />
          <button
            type="submit"
            className="px-6 py-4 text-lg font-bold text-white bg-blue-600 rounded-md"
          >
            Submit
          </button>
        </form>
        <ul
          className="flex items-center justify-center py-2 gap-4"
        >
          {data?.map((user) => (
            <li key={user.id} className="p-4 mb-4 text-xl border border-gray-300 rounded-md flex">
              <div>{user.name}</div>
              <button
                className="text-lg text-red-600"
                onClick={() => {
                  deleteuser({ id: user.id }).then(() => {
                    toast.success(`Deleted user ${user.name}`);
                    refetch();
                  })
                }}
              >
                <AiOutlineDelete />
              </button>
            </li>
          ))}
        </ul>
      </main>
    </>
  );
};

export default Home;
