import type { NextPage } from "next";
import Head from "next/head";
// import { toast } from "react-hot-toast";
import { api } from "~/utils/api";
import { UserButton, useSession } from "@clerk/nextjs";
import Link from "next/link";
import { useEffect } from "react";

const Home: NextPage = () => {

  const { mutateAsync: createUser } = api.users.createUser.useMutation();
  const { data, refetch } = api.users.getUsers.useQuery();
  // const { mutateAsync: deleteuser } = api.users.deleteUser.useMutation();
  //
  // function refetchHandler() {
  //   refetch()
  //     .catch(() => {
  //       toast.error(`Failed to refetch users`);
  //     });
  // }
  //

  const { session } = useSession();

  useEffect(() => {
    console.log(session);
  }, [session])

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {session && (
          <UserButton afterSignOutUrl="/" />
        )}
        {!session && (
          <div className="flex flex-col gap-2 p-2">
            <Link href="/sign-in">
              Sign In
            </Link>
          </div>
        )}
      </main>
    </>
  );
};

export default Home;
